config/routes.rb
Rails.application.routes.draw do
  get 'pages/home'

  resources :posts do 
    resources :comments, only:[:create,:destroy]
  end

  devise_for :users, controllers:{
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "posts#index"

end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id          :bigint           not null, primary key
#  name        :string
#  description :text
#  user_id     :bigint           not null
#  status      :integer          default(0)
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
class Post < ApplicationRecord

  has_one_attached :photo

  #validaciones
  validates :name, presence: true, uniqueness:true
  validates :description, presence: true
  
  #relaciones
  belongs_to :user
  has_many :comments, dependent: :destroy

  def self.ransackable_attributes(auth_object = nil)
    ["name"]
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index,:show]
  before_action :find_post, only: [:show,:edit, :update, :destroy]
  before_action except: [:index,:show] do 
    authorize_request(["admin"])
  end
  before_action :find_post_user, only:[:destroy,:update,:edit]
  def index
    @q = Post.ransack(params[:q])
    @posts = @q.result(distinct:true)
  end

  def new
     @post = current_user.posts.build
  end

  def create
    @post = current_user.posts.create(post_params)
    if @post.save
      redirect_to root_path, notice: "Se ha creado con éxito la noticia"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    
  end

  def update
    if @post.update(post_params)
      redirect_to @post, notice:'Se ha modificado con éxito'
    else
      render :edit,status: :unprocessable_entity
    end
  end

  def edit
  end

  def destroy
    @post.destroy
    redirect_to root_path, notice: "Se ha eliminado con éxito"
  end

  private 
  def find_post 
    @post =Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:name,:description, :photo)

  end

  def find_post_user
    if @post.id ==! current_user.id
      redirect_to root_path, alert: "No tienes autorización"
    end
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with model: post do |form| %>
    <div class="mb-6">
        <%= form.label :name, class:"block mb-2 text-sm font-medium text-gray-900 dark:text-white" %>
        <%= form.text_field :name, class:"bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"%>
        <% post.errors.full_messages_for(:name).each do |message| %>
            <div><%= message %></div>
        <% end %>

    </div>
    <div class="mb-6">
        <%= form.label :description, class:"block mb-2 text-sm font-medium text-gray-900 dark:text-white" %>
        <%= form.text_area :description, class:"block p-2.5 w-full text-sm text-gray-900 bg-gray-50 rounded-lg border border-gray-300 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" %>
        <% post.errors.full_messages_for(:description).each do |message| %>
            <div><%= message %></div>
        <% end %>
    </div>
    <div class="mb-6">

        <%= form.file_field :photo %>
    </div>

    <div class="mb-6">
        <%= form.submit class:"focus:outline-none text-white bg-green-700 hover:bg-green-800 focus:ring-4 focus:ring-green-300 font-medium rounded-lg text-sm px-5 py-2.5 mr-2 mb-2 dark:bg-green-600 dark:hover:bg-green-700 dark:focus:ring-green-800" %>
        <%= link_to "Volver atras", posts_path %>
    </div>
<% end %>

app/views/posts/_post.html.erb
<div class="max-w-sm p-6 bg-white border border-gray-200 rounded-lg shadow dark:bg-gray-800 dark:border-gray-700 flex-1">

    <h5 class="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white text-center"><%= post.name %></h5>

    <p class="mb-3 font-normal text-gray-700 dark:text-gray-400"><%= truncate(post.description,length:20) %></p>
    <%= link_to post_path(post), class:"inline-flex items-center px-3 py-2 text-sm font-medium text-center text-white bg-blue-700 rounded-lg hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800" do %>
       
            Read more
            <svg class="w-3.5 h-3.5 ml-2" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 10">
                <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M1 5h12m0 0L9 1m4 4L9 9"/>
            </svg>

    <% end %>
</div>

app/views/posts/edit.html.erb
<h2> Editar Post </h2>
<%= render "form", post: @post %>

app/views/posts/index.html.erb
<% if user_signed_in? %>
    <% if current_user.role == 'admin' %>
        <div class="ps-3">
            <p class="mb-2">Bienvenido estimado/a : <strong><%= current_user.name %></strong>  </p>
            <p class="mb-3">Tipo de usuario: <strong> <%= current_user.role %> </strong> </p>
            <%= link_to "Crear Post", new_post_path, class:"focus:outline-none text-white bg-green-700 hover:bg-green-800 focus:ring-4 focus:ring-green-300 font-medium rounded-lg text-sm px-5 py-2.5 my-5 dark:bg-green-600 dark:hover:bg-green-700 dark:focus:ring-green-800"%>
        </div>
    <% end %>
<% end %>

<h2 class="my-5 text-center md:text-start">Lista de noticias</h2>
<%= search_form_for @q, class:"mb-3" do |f|%>
  <%= f.hidden_field :name_cont  %>
  <%= f.search_field :name_cont, class:"rounded", placeholder:"search" %>
<% end %>
<div class="flex flex-col gap-3 md:flex-row md:flex-wrap">
    <% @posts.each do |post| %>
        <%= render partial: "post", locals: {post: post} %>
    <% end %>
</div>

app/views/posts/new.html.erb
<h2 class="mb-3 text-center md:text-start">Crear Post</h2>
<%= render "form", post: @post %>

app/views/posts/show.html.erb
<h2 class="text-gray-900 text-lg text-4x1 md:text-6xl dark:text-white text-center mt-3 md:text-8x1"><%= @post.name %></h2>
<div class="flex justify-between">  
    <p class="mb-4 mt-4">Creado por : <%= @post.user.name %> </p>
    <p> <%= @post.created_at %> </p>
</div>
<%= image_tag @post.photo, class:"h-auto max-w-full rounded-lg mb-5 mx-auto" if @post.photo.attached? %>


    <p class="mb-3"><%= @post.description %> </p>

<% if user_signed_in? %>
    
    <% if current_user.id == @post.user_id %>
       
        <%= link_to "Eliminar Noticia", post_path(@post), class:"focus:outline-none text-white bg-red-700 hover:bg-red-800 focus:ring-4 focus:ring-red-300 font-medium rounded-lg text-sm px-5 py-2.5 mr-2 mb-2 dark:bg-red-600 dark:hover:bg-red-700 dark:focus:ring-red-900 mt-3",
        data:{
            turbo_method: :delete,
            turbo_confirm: "Estás seguro?"
        }%>
        <%= link_to "Editar Noticia", edit_post_path(@post), class:"focus:outline-none text-white bg-yellow-400 hover:bg-yellow-500 focus:ring-4 focus:ring-yellow-300 font-medium rounded-lg text-sm px-5 py-2.5 mr-2 mb-2 dark:focus:ring-yellow-900" %>
    <% end %>
<% end %>
<%# LISTA DE COMENTARIOS %>
<h3 class="my-5 text-3xl text-gray-900 dark:text-white text-center">Lista de comentarios</h3>

<% @post.comments.each do |comment|%>
    <div class="grid grid-cols-2 divide-x border p-3">
        <div class="flex justify-between px-3">
            <p> Nombre: <%= comment.user.name %> </p>
            <p> <%= comment.created_at %> </p>
        </div>
        <div>
            <p class="ps-3"> <%= comment.body %> </p>
        </div>
    </div>
<% end %>
<% if user_signed_in? %>
    <%= form_with(model: [@post, @post.comments.build]) do |form|%>

        <%= form.label :body, class:"block mb-2 text-sm font-medium text-gray-900 dark:text-white" %>
        <%= form.text_area :body, class:"block p-2.5 w-full text-sm text-gray-900 bg-gray-50 rounded-lg border border-gray-300 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" %>

        <%= form.submit "Enviar Comentario", class:"mt-3 focus:outline-none text-white bg-purple-700 hover:bg-purple-800 focus:ring-4 focus:ring-purple-300 font-medium rounded-lg text-sm px-5 py-2.5 mb-2 dark:bg-purple-600 dark:hover:bg-purple-700 dark:focus:ring-purple-900" %>
    <% end %>
<% else %>
    Si quieres <%= link_to "Comentar", new_user_registration_path %> necesitas registrarte
<% end %>